---
- name: Install s/w's using yum and apt
  hosts: all
  tasks:
   - block:
      - name: Install tree using apt
        apt:
         name: tree
         state: present
         update_cache: yes
     rescue:
      - name: Install tree using yum
        yum:
         name: tree
         state: present
         update_cache: yes
...
