---
- name: Install/uninstall s/w applications
  hosts: all
  tasks:
  - name: Install s/w
    apt:
     name: "{{item}}"
     state: present
     update_cache: yes
    with_items:
     - tomcat9
     - git
     - maven
...
