---
- name: Create user on all managed nodes
  hosts: dbserver
  tasks:
   - name: create a user
     user:
      name: anu
      password: inttilqit
      uid: 1234
      home: /home/anu
      shell: /bin/bash
      comment: "A regular user"
...
