---
- name: Implementing playscope varibles
  hosts: all
  vars:
   - a: tomcat9
   - b: present
   - c: yes
  tasks:
   - name: Install s/w application
     apt:
      name: "{{a}}"
      state: "{{b}}"
      update_cache: "{{c}}"
...
