---
- name: Implementing tags
  hosts: all
  tasks:
   - name: Install tree
     apt:
      name: tree
      state: present
      update_cache: no
     tags: tree_installation
   - name: create user
     user:
      name: mahesh
      password: anurag
     tags: user_creation
   - name: Copy /etc/passwd file
     copy:
      src: /etc/passwd
      dest: /tmp
...
