---
- name: user creation with host scope variables
  hosts: 172.31.32.238
  tasks:
   - name: user creation
     user:
      name: "{{a}}"
      password: "{{b}}"
      home: "{{c}}"
      uid: "{{d}}"
      comment: "{{e}}"
      shell: "{{f}}"
...
